# Generated by Django 5.2.3 on 2025-07-04 13:12

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=music.models.artist_profile_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to=music.models.song_cover_path),
        ),
    ]
